import { useState } from 'react';
import { Link } from '../../lib/router';
import { useStaffPathState } from '../../lib/appStore';
import { buildCoachActions, retrieveCoachMatches } from './recommendations';

export function CoachPage() {
  const state = useStaffPathState(); const actions = buildCoachActions(state); const [query, setQuery] = useState(''); const [submitted, setSubmitted] = useState('');
  const matches = submitted ? retrieveCoachMatches(submitted) : { chapters: [], scenarios: [] };
  return <div className="page coach-page"><div className="page-heading"><div><p className="eyebrow">PRIVATE · EVIDENCE-AWARE · LOCAL</p><h1>Your preparation coach</h1><p>StaffPath recommends the next useful action from your real progress and retrieves material already in your source of truth.</p></div></div><section className="coach-priorities"><div><p className="eyebrow">NEXT BEST ACTIONS</p><h2>Do less, deliberately.</h2></div><div>{actions.map((action, index) => <Link key={action.title} to={action.to}><span>0{index + 1}</span><div><strong>{action.title}</strong><p>{action.reason}</p></div><em>→</em></Link>)}</div></section><section className="coach-search"><p className="eyebrow">ASK YOUR KNOWLEDGE BASE</p><h2>Find a concept or practice problem</h2><form onSubmit={(event) => { event.preventDefault(); setSubmitted(query.trim()); }}><input aria-label="Coach question" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="e.g. How do I prevent duplicate payment processing?" /><button className="button primary" disabled={!query.trim()}>Find guidance</button></form>{submitted && <div className="coach-results"><p>Results are retrieved from curated StaffPath content; this local coach does not fabricate an open-ended answer.</p><div>{matches.chapters.map((chapter) => <Link to="/encyclopedia" key={chapter.id}><span>CHAPTER</span><strong>{chapter.title}</strong><p>{chapter.summary}</p></Link>)}{matches.scenarios.map((scenario) => <Link to="/practice" key={scenario.id}><span>PRACTICE</span><strong>{scenario.title}</strong><p>{scenario.prompt}</p></Link>)}{!matches.chapters.length && !matches.scenarios.length && <div className="interview-empty">No strong local match. Try concrete terms such as caching, payments, conflict, migration, RAG, or rate limiting.</div>}</div></div>}</section></div>;
}
