import { useState } from 'react';
import { appStore, useStaffPathState } from '../../lib/appStore';

export function JournalPage() {
  const state = useStaffPathState();
  const [learning, setLearning] = useState(''); const [application, setApplication] = useState(''); const [artifact, setArtifact] = useState(''); const [tags, setTags] = useState(''); const [quality, setQuality] = useState(3);
  function save(event: React.FormEvent) { event.preventDefault(); if (!learning.trim()) return; appStore.update((current) => ({ ...current, journal: [...current.journal, { id: crypto.randomUUID(), date: new Date().toISOString(), learning: learning.trim(), application: application.trim(), artifact: artifact.trim(), quality, tags: tags.split(',').map((tag) => tag.trim()).filter(Boolean) }] })); setLearning(''); setApplication(''); setArtifact(''); setTags(''); setQuality(3); }
  return <div className="page journal-page"><div className="page-heading"><div><p className="eyebrow">REFLECT → ADAPT → RETRIEVE</p><h1>Learning journal</h1><p>Turn activity into durable judgment and searchable evidence.</p></div><div className="chapter-count"><strong>{state.journal.length}</strong><span>reflections</span></div></div><div className="journal-layout"><form className="journal-form" onSubmit={save}><h2>Capture a reflection</h2><label>What changed in your thinking?<textarea aria-label="Journal learning" required value={learning} onChange={(event) => setLearning(event.target.value)} /></label><label>Where will you apply it?<textarea aria-label="Journal application" value={application} onChange={(event) => setApplication(event.target.value)} /></label><label>Artifact or evidence<input aria-label="Journal artifact" value={artifact} onChange={(event) => setArtifact(event.target.value)} placeholder="Link, filename, diagram, feedback…" /></label><label>Tags<input aria-label="Journal tags" value={tags} onChange={(event) => setTags(event.target.value)} placeholder="reliability, influence, migration" /></label><label className="confidence-row"><span>Learning quality</span><input aria-label="Learning quality" type="range" min="1" max="5" value={quality} onChange={(event) => setQuality(Number(event.target.value))} /><strong>{quality}/5</strong></label><button className="button primary" disabled={!learning.trim()}>Save reflection</button></form><section className="journal-entries"><h2>Evidence timeline</h2>{state.journal.slice().reverse().map((entry) => <article key={entry.id}><div><span>{new Date(entry.date).toLocaleDateString()}</span><strong>QUALITY {entry.quality}/5</strong></div><h3>{entry.learning}</h3>{entry.application && <p>{entry.application}</p>}{entry.tags.length > 0 && <div className="topic-cloud">{entry.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>}{entry.artifact && <em>Artifact · {entry.artifact}</em>}</article>)}{!state.journal.length && <div className="interview-empty">No reflections yet. Capture the insight that should change your next decision.</div>}</section></div></div>;
}
